<a href="https://colab.research.google.com/github/jaykkim1/KNOC_KPA_2025/blob/main/KPA_%EC%8B%A4%EC%8A%B5_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello, world!")

Hello, world!


In [ ]:
import os

# 현재 작업 디렉토리 확인
current_dir = os.getcwd()
print("현재 디렉토리:", current_dir)


현재 디렉토리: /content


# 1. 변수와 자료형

In [ ]:
company = "한국석유공사"
location = 'ulsan'
yr_est= 1979
my_company = True
print(company, location, yr_est, my_company)

한국석유공사 ulsan 1979 True


In [ ]:
# print문 활용

#1. 콤마를 찍으면 여러개 값을 출력할수 있음
a = 25
print(10, '10', '볼펜', a, True)

#2. f-string
b= '울산'
print(f'한국석유공사는 {b}에 위치하고 있습니다.')


10 10 볼펜 25 True
한국석유공사는 울산에 위치하고 있습니다.


# 2. 리스트

In [ ]:
fruits = ["사과", "바나나", "딸기"]
print(fruits[0])    # 사과
print(fruits[1:3])  # ['바나나', '딸기']

사과
['바나나', '딸기']


In [ ]:
fruits[0] = '오렌지'
fruits

['오렌지', '바나나', '딸기']

#3. 튜플과 딕셔너리

In [ ]:
person = ("홍길동", 30)  # 튜플
employee = {"이름": "김철수", "부서": "영업"}  # 딕셔너리

print(person[0])          # 홍길동
print(person[1])          # 30
print(employee["이름"])   # 김철수

홍길동
30
김철수


#4. 조건문

In [ ]:
score = 85
if score >= 90:
    print("우수")
elif score >= 70:
    print("보통")
else:
    print("미흡")

보통


# 5. 반복문

In [ ]:
# for 반복문

fruits = ["사과", "바나나", "딸기"]
for fruit in fruits:
    print(fruit)

사과
바나나
딸기


In [ ]:
for i in range(2,10,2):
  print(f'{round(i/2)}번째 반환 숫자는 {i}입니다')

1번째 반환 숫자는 2입니다
2번째 반환 숫자는 4입니다
3번째 반환 숫자는 6입니다
4번째 반환 숫자는 8입니다


In [ ]:
# while 반복문

count = 0
while count < 3:
    print("반복 중:", count)
    count += 1

반복 중: 0
반복 중: 1
반복 중: 2


In [ ]:
count = 0
while count < 3:
    print("반복 중:", count)
    count = count + 2

반복 중: 0
반복 중: 2


# 6. 기초연산

In [ ]:
a = 10
b = 7
c= a+b

print('c =', c) # 더하기: 연산된 변수 반환
print('a + b =', a+b) # 더하기: 직접 계산

print('a - b =', a-b) # 빼기

print('a/b =', a/b) # 나누기

print('a*b =', a*b) # 곱하기

print('a^b =', a**b) # 거듭제곱

print('a/b 몫 =', a//b) # 나누기 몫


import numpy as np
print(np.round(a/b, 3)) #나누기 후 소숫점 세자리에서 반올림



c = 17
a + b = 17
a - b = 3
a/b = 1.4285714285714286
a*b = 70
a^b = 10000000
a/b 몫 = 1
1.429


In [ ]:
# Q. 반복문과 f-string을 활용한 실습: 구구단 2단(for문)
number = 2

print(f'*{number}단 시작')
for i in range(1, 10):
  result = number * i
  print(f"{number} x {i} = {result}")

*2단 시작
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18


In [ ]:
# Q. 반복문과 f-string을 활용한 실습: 구구단 2단(while문)
number = 2
i = 1
print(f'*{number}단 시작')
while i < 10:
  result = number * i
  print(f"{number} x {i} = {result}")
  i = i + 1

*2단 시작
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18


In [ ]:
# Q. 반복문과 f-string을 활용한 실습: 구구단(for문)


for number in range(2,10):
  print(f'*{number}단 시작')
  for i in range(1,10): # [1,2,3,4,5,6,7,8,9] 직접 리스트로 작성해도 됨
    result = number * i
    print(f"{number} x {i} = {result}")


*2단 시작
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
*3단 시작
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
*4단 시작
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
*5단 시작
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
*6단 시작
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
*7단 시작
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
*8단 시작
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
*9단 시작
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81


In [ ]:
# Q. 반복문과 f-string을 활용한 실습: 구구단(while문)

number = 2

while number <10:
  print(f'*{number}단 시작')
  for i in range(1, 10):
    result = number * i
    print(f"{number} x {i} = {result}")
  number = number + 1


*2단 시작
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
*3단 시작
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
*4단 시작
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
*5단 시작
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
*6단 시작
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
*7단 시작
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
*8단 시작
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
*9단 시작
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81


#7. 함수

In [ ]:
def muliply(a,b):
  c = a*b
  return c

print(muliply(2,3))



6


In [ ]:
# 수포화도 계산 함수
def archie_sw(Rt, Rw, phi, a, m, n):
    """
    Archie 방정식으로 수포화도 계산

    Parameters:
    Rt : float - true resistivity (ohm-m)
    Rw : float - formation water resistivity (ohm-m)
    phi : float - porosity (0~1 사이)
    a : float - tortuosity factor
    m : float - cementation exponent
    n : float - saturation exponent

    Returns:
    Sw : float - 수포화도 (0~1 사이)
    """
    if phi <= 0 or Rt <= 0 or Rw <= 0:
        raise ValueError("공극률, Rt, Rw 값은 모두 양수여야 합니다.")

    Sw = ((a / (phi ** m)) * (Rw / Rt)) ** (1 / n)
    return Sw


Rt = 10.25
Rw= 0.05
phi= 0.2
a = 1
m = 2
n = 2

archie_sw(Rt, Rw, phi, a, m, n)

0.3492151478847891

In [ ]:
import numpy as np
import pandas as pd

def RT_calc(a, RW, PHI, SW, m, n):
  RT = (a*RW)/((PHI**m)*(SW**n))
  RT = round(RT,3)
  return RT

a = 1
RW = 0.018
PHI = 0.14
SW = 0.4
m = 1.94
n = 2.03


PHI_range = np.arange(0.11,0.16,0.005)
SW_range = np.arange(0.1,1.1,0.1)
result = pd.DataFrame(index=PHI_range, columns=SW_range)

for i in PHI_range:
  for j in SW_range:
    # print(RT_calc(a, RW, i, j, m, n))

    result.loc[i,j] = round(RT_calc(a, RW, i, j, m, n),3)

print("RT sensitivity w/ SW(column) & PHIT(row)")
result

RT sensitivity w/ SW(column) & PHIT(row)


0.1     0.2     0.3    0.4    0.5    0.6    0.7    0.8    0.9  \
0.110  139.627  34.188  15.011  8.371  5.322  3.676  2.688   2.05  1.614   
0.115  128.091  31.364  13.771   7.68  4.882  3.372  2.466   1.88   1.48   
0.120   117.94  28.878   12.68  7.071  4.495  3.105   2.27  1.731  1.363   
0.125   108.96  26.679  11.714  6.533  4.153  2.868  2.098    1.6  1.259   
0.130  100.977  24.725  10.856  6.054  3.849  2.658  1.944  1.482  1.167   
0.135   93.848  22.979  10.089  5.627  3.577   2.47  1.807  1.378  1.085   
0.140   87.455  21.414   9.402  5.243  3.333  2.302  1.684  1.284  1.011   
0.145   81.699  20.004   8.783  4.898  3.114  2.151  1.573  1.199  0.944   
0.150   76.499  18.731   8.224  4.586  2.916  2.014  1.473  1.123  0.884   
0.155   71.784  17.577   7.717  4.304  2.736   1.89  1.382  1.054   0.83   

         1.0  
0.110  1.303  
0.115  1.195  
0.120  1.101  
0.125  1.017  
0.130  0.942  
0.135  0.876  
0.140  0.816  
0.145  0.762  
0.150  0.714  
0.155   0.67

#8. 주요 라이브러리와 import문법

In [ ]:
# 넘파이
import numpy as np

a = np.array([1, 2, 3, 4])    # 1차원 배열
b = np.array([[1, 2], [3, 4]]) # 2차원 배열 (행렬)
print(a)
print(b)

print(np.shape(a))
print(np.shape(b))

[1 2 3 4]
[[1 2]
 [3 4]]
(4,)
(2, 2)


In [ ]:
b[1][0]

np.int64(3)

In [ ]:
b*2

array([[2, 4],
       [6, 8]])

In [ ]:
# 넘파이 배열 연산
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)    # [5 7 9]
print(x * y)    # 원소별 곱 [4 10 18]
print(x.dot(y)) # 내적  (1*4 + 2*5 + 3*6) = 32

[5 7 9]
[ 4 10 18]
32


In [ ]:
# 난수 배열 생성
rand_array = np.random.rand(5)  # 0~1 사이 균등분포 난수 5개
rand_int = np.random.randint(0, 10, size=5) # 0~9 사이 정수 난수 5개
print(rand_array)
print(rand_int)

[0.86652579 0.59603649 0.95419296 0.29136497 0.4541446 ]
[1 4 5 1 6]


In [ ]:
data = np.array([1, 2, 3, 4, 5])
print(np.mean(data))   # 평균 3.0
print(np.median(data)) # 중앙값 3.0
print(np.std(data))    # 표준편차

3.0
3.0
1.4142135623730951


In [ ]:
# 실습
import numpy as np
test_list = [1,2,3]
test_np = np.array(test_list)
print(test_list)
print(test_np)

[1, 2, 3]
[1 2 3]


In [ ]:
print(test_list*2)
print(test_list+test_list)
print(test_np*2)
print(test_np+2)

[1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3]
[2 4 6]
[3 4 5]


In [ ]:
# 판다스

import pandas as pd

data = {
    '이름': ['김철수', '이영희', '박민수'],
    '나이': [25, 30, 22],
    '성별': ['남', '여', '남']
}
df = pd.DataFrame(data)
print(df)

    이름  나이 성별
0  김철수  25  남
1  이영희  30  여
2  박민수  22  남


In [ ]:
df.to_csv('output.csv', index=False)  # CSV 파일로 저장 (인덱스 제외)
df = pd.read_csv('output.csv')   # CSV 파일 읽기
df

이름  나이 성별
0  김철수  25  남
1  이영희  30  여
2  박민수  22  남

In [ ]:
df.to_excel('output.xlsx', index=False)  # xlsx 파일로 저장 (인덱스 제외)
df = pd.read_excel('output.xlsx')   # xlsx 파일 읽기
df

이름  나이 성별
0  김철수  25  남
1  이영희  30  여
2  박민수  22  남

In [ ]:
print(df.head(1))       # 상위 1개 행 출력
print("\n",df.tail(2))      # 하위 2개 행 출력
print("\n",df['이름'])      # 특정 열 조회 (Series 형태)
print("\n",df.loc[0])       # 첫번째 행(0번 행인덱스) 조회 (Series)
print("\n",df.iloc[1:3])    # 2~3번째 행(1~2번행) 슬라이싱 (DataFrame)
print("\n",df.iloc[:,2])    # 1번째 열 조회 (Series)


    이름  나이 성별
0  김철수  25  남

     이름  나이 성별
1  이영희  30  여
2  박민수  22  남

 0    김철수
1    이영희
2    박민수
Name: 이름, dtype: object

 이름    김철수
나이     25
성별      남
Name: 0, dtype: object

     이름  나이 성별
1  이영희  30  여
2  박민수  22  남

 0    남
1    여
2    남
Name: 성별, dtype: object


In [ ]:
# 나이가 25 이상인 행만
filtered = df[df['나이'] >= 25]
print(filtered)

    이름  나이 성별
0  김철수  25  남
1  이영희  30  여


In [ ]:
print(df.describe())       # 수치형 컬럼 기초 통계
print("\n",df['나이'].mean())   # 나이 평균
print("\n",df['성별'].value_counts())  # 성별 개수 세기

              나이
count   3.000000
mean   25.666667
std     4.041452
min    22.000000
25%    23.500000
50%    25.000000
75%    27.500000
max    30.000000

 25.666666666666668

 성별
남    2
여    1
Name: count, dtype: int64


In [ ]:
#판다스: 데이터 프레임에 열추가
df['나이-10세'] = df['나이'] - 10
df

이름  나이 성별  나이-10세
0  김철수  25  남      15
1  이영희  30  여      20
2  박민수  22  남      12

In [ ]:
#판다스: 데이터 프레임에 행추가

new_row = pd.DataFrame({'이름': ['이지원'], '나이': [23], '성별': ['여'],
                        '성인여부': True, '나이-10세': 13 })
df_rev = pd.concat([df, new_row], ignore_index=True)

df_rev

이름  나이 성별  나이-10세  성인여부
0  김철수  25  남      15   NaN
1  이영희  30  여      20   NaN
2  박민수  22  남      12   NaN
3  이지원  23  여      13  True

# CSV 및 xlsx 파일로 저장

In [ ]:
df.to_excel("KPA_test_1.xlsx")
df.to_csv("KPA_test_1.csv", encoding='utf-8-sig')