<a href="https://colab.research.google.com/github/jaykkim1/KNOC_KPA_2025/blob/main/KPA%EC%8B%A4%EC%8A%B5_%EC%B6%94%EA%B0%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. 정규화 (Normalization)

데이터를 특정 범위(주로 [0, 1])로 스케일링하는 과정.

In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# 예시 데이터
data = np.array([[10], [15], [20], [25], [30]])

scaler = MinMaxScaler()
normalized = scaler.fit_transform(data)

print("원본 데이터:\n", data)
print("\n정규화된 데이터:\n", normalized)

원본 데이터:
 [[10]
 [15]
 [20]
 [25]
 [30]]

정규화된 데이터:
 [[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


2. 표준화 (Standardization)

데이터를 평균 0, 표준편차 1의 분포로 변환.
정규분포(가우시안 분포)를 가정하는 모델(예: 선형 회귀, 로지스틱 회귀, PCA)에 주로 사용.

In [2]:
from sklearn.preprocessing import StandardScaler

# 예시 데이터
data = np.array([[10], [15], [20], [25], [30]])

scaler = StandardScaler()
standardized = scaler.fit_transform(data)

print("원본 데이터:\n", data)
print("\n표준화된 데이터:\n", standardized)

원본 데이터:
 [[10]
 [15]
 [20]
 [25]
 [30]]

표준화된 데이터:
 [[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]
